spring:
  application:
    name: talk
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mongodb:
    uri: mongodb+srv://levannhatbao29_db_user:LGfwtMev14cXyH4E@cluster-jv-baole.gqk85p4.mongodb.net/talk?appName=Cluster-JV-BaoLe
  datasource:
    url: jdbc:postgresql://localhost:5432/talktalk
    username: postgres
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: localhost
    port: 6379
  mail:
    host: smtp.gmail.com
    port: 587
    username: levannhatbao29@gmail.com
    password: tdqh lljk ygem kvgv
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

jwt:
  secret: Do8q4JpVmM0UST7pIvpGUMXdXMH0wlF0z6RHXm6d1XQ=
  validDuration: 60000m
  refreshableDuration: 7d

cloudinary:
  cloud-name: dwezdjte2
  api-key: 383514231542653
  api-secret: IpwVbYPSj4XLx10H6f6H_oUz8rY

