spring:
  application:
    name: talk
  data:
    mongodb:
      uri: mongodb+srv://${MONGO_ROOT_USERNAME:levannhatbao29_db_user}:${MONGO_ROOT_PASSWORD:LGfwtMev14cXyH4E}@cluster-jv-baole.gqk85p4.mongodb.net/talk?appName=Cluster-JV-BaoLe
  datasource:
    url: jdbc:postgresql://postgres:5432/${POSTGRES_DB:talktalk}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:123456}
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
  redis:
    host: redis
    port: 6379
